#!/usr/bin/env bash

url="http://localhost:3000/shops"

newShop=$(curl -X GET "$url/new")

echo "GET all (list)"
curl -X GET $url

echo "GET at index 0"
curl -X GET "http://localhost:3000/shops/0"

echo "POST new shop"
curl -X POST $url --header "Content-Type: application/json" --data "$newShop"

echo "PUT at index 0"
curl -X PUT "$url/0" --header "Content-Type: application/json" --data "$newShop"

echo "DELETE at index 0"
curl -X DELETE "$url/0"
