#!/usr/bin/env bash

rurl="https://git.generalassemb.ly/atl-wdi/sei-curriculum.git" 
localdir="$1"
cloneDir="sequences/$1"

mkdir -p "$localdir"
cd "$localdir"

git init
git remote add origin "$rurl"

git config core.sparseCheckout true

# Loops over remaining args
echo $cloneDir >> .git/info/sparse-checkout

git pull origin master

rm -rf .git
mv $cloneDir/* .
rm -r sequences
